# Generated by Django 4.1 on 2022-09-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_repo", "0002_contact_information_scqcurrent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact_information",
            name="contact_pref_phone",
        ),
        migrations.RemoveField(
            model_name="contact_information",
            name="contact_pref_phone_display_value",
        ),
        migrations.AddField(
            model_name="contact_information",
            name="contact_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact_information",
            name="contact_official_contact",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="landing_page",
            name="landing_consent_trigger",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eyetracking",
            name="eyetrack_emot_face_gaze",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eyetracking",
            name="eyetrack_fss_2017_gaze",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
