"""
Django settings for chiron_dev2 project.

Generated by 'django-admin startproject' using Django 2.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['10.23.20.171', '10.23.20.189', '127.0.0.1', 'localhost',
    'chi-dev.uc.edu', 'chi-test.uc.edu', 'chi-tools.uc.edu', 'chi.uc.edu']


# Application definition

sys.path.append("../")

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'crispy_forms',
    
    'user_manager',
    
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'user_manager.middleware.ChiAuthLoginMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'project.context_processors.settings_context_processor',
                'user_manager.context_processors.settings_context_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_L10N = False

USE_TZ = False

DATE_FORMAT = 'm/d/Y'




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/




STATIC_URL = '/static/'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

LOGIN_URL = '/user_manager/login'
LOGIN_URL_FOR_LINK = '/user_manager/login'
LOGOUT_URL_FOR_LINK = '/user_manager/logout'

SITE_TITLE = 'My Website'
SITE_CONTACT_EMAIL = 'meinkejf@ucmail.uc.edu'


AUTH_USER_MODEL = "user_manager.User"

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'user_manager.authentication_backends.ChiAuthBackend',
]

CHI_AUTH_AUTOCREATE_LOCAL_USER = True
CHI_AUTH_CHECK_SYSTEMS = 'local, ucad'
CHI_AUTH_AUTOCREATE_CHI_AUTH_USER = False            # when local user is created, signal is used to create the user in CHI_AUTH as well

LOGIN_URL = '/user_manager/login'                   # this url gets called when @login_required view is accessed
LOGIN_URL_FOR_LINK = '/user_manager/login'          # use as a sign in link <a href="{{ LOGIN_URL_FOR_LINK }}">Sign In</a>
LOGOUT_URL_FOR_LINK = '/user_manager/logout'        # use as a sign out link <a href="{{ LOGOUT_URL_FOR_LINK }}">Sign Out</a>







