# Generated by Django 4.1 on 2022-09-20 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instrument_name", models.CharField(max_length=255)),
                (
                    "orig_study_field_name",
                    models.CharField(
                        help_text="The name of the field where the original study value should go.",
                        max_length=255,
                    ),
                ),
                (
                    "studies_field_name",
                    models.CharField(
                        help_text="The name of the field where the original study value should go.",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("study_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="StudyInstrument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_age",
                    models.FloatField(
                        blank=True, help_text="Leave blank for no min age", null=True
                    ),
                ),
                (
                    "max_age",
                    models.FloatField(
                        blank=True, help_text="Leave blank for no max age", null=True
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.instrument",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.study"
                    ),
                ),
            ],
        ),
    ]
