# Generated by Django 4.1 on 2022-09-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="study",
            options={"verbose_name_plural": "studies"},
        ),
        migrations.AddField(
            model_name="study",
            name="study_number",
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="instrument",
            name="instrument_name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="study",
            name="study_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
